CREATE TABLE `playercreateinfo` (                            
                    `createId` tinyint(3) unsigned NOT NULL auto_increment,    
                    `race` tinyint(3) unsigned NOT NULL default '0',           
                    `class` tinyint(3) unsigned NOT NULL default '0',          
                    `map` mediumint(8) unsigned NOT NULL default '0',          
                    `zone` mediumint(8) unsigned NOT NULL default '0',         
                    `position_x` float NOT NULL default '0',                   
                    `position_y` float NOT NULL default '0',                   
                    `position_z` float NOT NULL default '0',                   
                    `displayID` smallint(5) unsigned NOT NULL default '0',     
                    `BaseStrength` tinyint(3) unsigned NOT NULL default '0',   
                    `BaseAgility` tinyint(3) unsigned NOT NULL default '0',    
                    `BaseStamina` tinyint(3) unsigned NOT NULL default '0',    
                    `BaseIntellect` tinyint(3) unsigned NOT NULL default '0',  
                    `BaseSpirit` tinyint(3) unsigned NOT NULL default '0',     
                    `BaseArmor` mediumint(8) unsigned NOT NULL default '0',    
                    `BaseHealth` mediumint(8) unsigned NOT NULL default '0',   
                    `BaseMana` mediumint(8) unsigned NOT NULL default '0',     
                    `BaseRage` mediumint(8) unsigned NOT NULL default '0',     
                    `BaseFocus` mediumint(8) unsigned NOT NULL default '0',    
                    `BaseEnergy` mediumint(8) unsigned NOT NULL default '0',   
                    PRIMARY KEY  (`createId`),                                 
                    KEY `playercreateinfo_index` (`race`,`class`)              
                  ) ENGINE=MyISAM AUTO_INCREMENT=53 DEFAULT CHARSET=utf8       
